// Application main form file.
 
// Original file name: App_RenRenMainForm.h
// Generated by TOPS Builder:Project wizard,Date:2010-12-13
 

 
#ifndef  __App_RenRen_MainForm_H__
#define  __App_RenRen_MainForm_H__
#include "TG3.h"

#define LOADING_FORM_DOT_NUM		(5)

class TMainForm : public TWindow
{
public:

	TMainForm(TApplication * pApp);

	~TMainForm(void);

public:
	virtual Boolean EventHandler(TApplication * pApp, EventType * pEvent);
protected:
	Boolean _OnCtlSelectEvent( TApplication * pApp,EventType * pEvent );
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	void _DrawDot(TApplication * pApp, int nStep);	
private:
	int	nLoadStep;
	Int32 nDotID[LOADING_FORM_DOT_NUM];
	Int32 m_nTimerId;	
};
 

#endif

