// Application main header  file.
 
// Original file name: App_RenRenEntry.h
// Generated by TOPS Builder:Project wizard,Date:2010-12-13
 


#ifndef  __App_RenRen_Main_H__
#define  __App_RenRen_Main_H__
#include "TG3.h"

#endif

