/*!
*@FileName: RenRenAPI_UsersGetEvent.cpp
*@Author: zbingwen@GoZone
*@Date: 2010-12-24
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by ReeRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#include "RenRenAPICommon.h"

/**
 * Json文件解析
 *
 * \param text
 *
 * \return 
 */
void* RenRenAPI_JsonParse_UsersGetEvent(char *text)
{
	cJSON *json;
	cJSON *pTemp0;
	tResponseUsersGetEvent*  Response = new tResponseUsersGetEvent;
	memset(Response, 0 , sizeof(tResponseUsersGetEvent));

	json = cJSON_Parse(text);

	//共有数据, 统一处理
	pTemp0 = cJSON_GetObjectItem(json, "friend_request_count");
	if(pTemp0)
	{
		Response->friend_request_count = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "new_message_count");
	if(pTemp0)
	{
		Response->new_message_count = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "poke_count");
	if(pTemp0)
	{
		Response->poke_count = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "fangle_count");
	if(pTemp0)
	{
		Response->fangle_count = pTemp0->valueint;
	}



	cJSON_Delete(json);
	return Response;
}