/*!
*@FileName: RenRenAPI_dealFriendRequest.h
*@Author: zbingwen@GoZone
*@Date: 2010-12-30
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_DEALFRIENDREQUEST_H__
#define  __RENRENAPI_DEALFRIENDREQUEST_H__

#include "RenRenAPI.h"

typedef struct
{
	int result;
}tResponsedealFriendRequest;


extern void* RenRenAPI_JsonParse_dealFriendRequest(char *text);
#endif
