/*!
*@FileName: RenRenAPI_UsersGetInfo.h
*@Author: pengzhixiong@GoZone
*@Date: 2010-12-29
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_USERSGETINFO_H__
#define  __RENRENAPI_USERSGETINFO_H__

#include "RenRenAPI.h"

typedef struct
{
	char country[32 + 1];
	char province[32 + 1];
	char city[32 + 1];
}UsersGetInfo_hometown_location;

typedef struct
{
	char company_name[64 + 1];
	char description[256 + 1];
	char start_date[64 + 1];
	char end_date[64 + 1];
}UsersGetInfo_work_history;

typedef struct
{
	char name[64 + 1];
	int year;
	char department[128 + 1];
}UsersGetInfo_university_history;

typedef struct
{
	char name[64 + 1];
	int grad_year;
}UsersGetInfo_hs_history;

typedef struct
{
	char msn[128 + 1];
	char mobile_tel[64 + 1];
	char telephone[64 + 1];
	char web_site[128 + 1];
	char qq[64 + 1];
}UsersGetInfo_contact_info;

typedef struct
{
	int uid;
	char name[32 + 1];
	int sex;
	int star;
	int zidou;
	char birthday[64 + 1];
	char email_hash[256 + 1];
	char tinyurl[256 + 1];
	char headurl[256 + 1];
	char mainurl[256 + 1];
	int  nSize_hometown_location;  //Save the array size by code_gen tools. 
	UsersGetInfo_hometown_location*  hometown_location;
	int  nSize_work_history;  //Save the array size by code_gen tools. 
	UsersGetInfo_work_history*  work_history;
	int  nSize_university_history;  //Save the array size by code_gen tools. 
	UsersGetInfo_university_history*  university_history;
	int  nSize_hs_history;  //Save the array size by code_gen tools. 
	UsersGetInfo_hs_history*  hs_history;
	int  nSize_contact_info;  //Save the array size by code_gen tools. 
	UsersGetInfo_contact_info*  contact_info;
}tResponseUsersGetInfoItem;

typedef struct
{
	int	nArraySize;
	tResponseUsersGetInfoItem*	Array;
}tResponseUsersGetInfo;


extern void* RenRenAPI_JsonParse_UsersGetInfo(char *text);
#endif
