/*!
*@FileName: RenRenAPI_StatusGetComment.h
*@Author: zbingwen@GoZone
*@Date: 2011-1-10
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_STATUSGETCOMMENT_H__
#define  __RENRENAPI_STATUSGETCOMMENT_H__

#include "RenRenAPI.h"

typedef struct
{
	int uid;
	char name[255 + 1];
	char tinyurl[255 + 1];
	int status_id;
	char time[255 + 1];
	char text[1024 + 1];
}tResponseStatusGetCommentItem;

typedef struct
{
	int	nArraySize;
	tResponseStatusGetCommentItem*	Array;
}tResponseStatusGetComment;


extern void* RenRenAPI_JsonParse_StatusGetComment(char *text);
#endif
