/*!
*@FileName: RenRenAPI_dealFriendRequest.cpp
*@Author: zbingwen@GoZone
*@Date: 2010-12-30
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by ReeRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#include "RenRenAPICommon.h"

/**
 * JsonÎÄ¼þ½âÎö
 *
 * \param text
 *
 * \return 
 */
void* RenRenAPI_JsonParse_dealFriendRequest(char *text)
{
	cJSON *json;
	cJSON *pTemp0;
	tResponsedealFriendRequest*  Response = new tResponsedealFriendRequest;
	memset(Response, 0 , sizeof(tResponsedealFriendRequest));

	json = cJSON_Parse(text);

	pTemp0 = cJSON_GetObjectItem(json, "result");
	if(pTemp0)
	{
		Response->result = pTemp0->valueint;
	}



	cJSON_Delete(json);
	return Response;
}