/*!
*@FileName: RenRenAPI_MessageGet.h
*@Author: pengzhixiong@GoZone
*@Date: 2010-12-24
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_MESSAGEGET_H__
#define  __RENRENAPI_MESSAGEGET_H__

#include "RenRenAPI.h"

typedef struct
{
	int uid;
	char name[64 + 1];
	char head_url[255 + 1];
	char time[64 + 1];
	char content[40960 + 1];		//内容最大暂定40K
}MessageGet_message;

typedef struct
{
	int  nSize_message;  //Save the array size by code_gen tools. 
	MessageGet_message*  message;
}tResponseMessageGet;


extern void* RenRenAPI_JsonParse_MessageGet(char *text);
#endif
