/*!
*@FileName: RenRenAPI_StatusGetComment.cpp
*@Author: zbingwen@GoZone
*@Date: 2011-1-10
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by ReeRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#include "RenRenAPICommon.h"

/**
 * JsonÎÄ¼þ½âÎö
 *
 * \param text
 *
 * \return 
 */
void* RenRenAPI_JsonParse_StatusGetComment(char *text)
{
	int i = 0;
	cJSON *jsonall;
	cJSON *json;
	cJSON *pTemp0;
	tResponseStatusGetComment*  Response = new tResponseStatusGetComment;
	memset(Response, 0 , sizeof(tResponseStatusGetComment));

	jsonall = cJSON_Parse(text);

	Response->nArraySize = cJSON_GetArraySize(jsonall);
	if(Response->nArraySize>0)
	{
		Response->Array = (tResponseStatusGetCommentItem*) malloc(sizeof( tResponseStatusGetCommentItem) * Response->nArraySize );
		memset(Response->Array, 0 , sizeof(tResponseStatusGetCommentItem) * Response->nArraySize);
		for(i = 0; i<Response->nArraySize; i++)
		{
			json = cJSON_GetArrayItem(jsonall, i);

			pTemp0 = cJSON_GetObjectItem(json, "uid");
			if(pTemp0)
			{
				Response->Array[i].uid = pTemp0->valueint;
			}
			pTemp0 = cJSON_GetObjectItem(json, "name");
			if(pTemp0)
			{
				STRCPY_Ex(Response->Array[i].name, pTemp0->valuestring);
			}
			pTemp0 = cJSON_GetObjectItem(json, "tinyurl");
			if(pTemp0)
			{
				STRCPY_Ex(Response->Array[i].tinyurl, pTemp0->valuestring);
			}
			pTemp0 = cJSON_GetObjectItem(json, "status_id");
			if(pTemp0)
			{
				Response->Array[i].status_id = pTemp0->valueint;
			}
			pTemp0 = cJSON_GetObjectItem(json, "time");
			if(pTemp0)
			{
				STRCPY_Ex(Response->Array[i].time, pTemp0->valuestring);
			}
			pTemp0 = cJSON_GetObjectItem(json, "text");
			if(pTemp0)
			{
				STRCPY_Ex(Response->Array[i].text, pTemp0->valuestring);
			}



		}
	}
	cJSON_Delete(jsonall);
	return Response;
}
