/*!
*@FileName: RenRenAPI_PagesGetInfo.h
*@Author: pengzhixiong@GoZone
*@Date: 2010-12-28
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_PAGESGETINFO_H__
#define  __RENRENAPI_PAGESGETINFO_H__

#include "RenRenAPI.h"

typedef struct
{
	int status_id;
	char content[1024 + 1];
	char time[64 + 1];
}PagesGetInfo_status;

typedef struct
{
	char info[255 + 1];
	char key[128 + 1];
	char value[1024 + 1];
}PagesGetInfo_base_info;

typedef struct
{
	char info[256 + 1];
	char key[128 + 1];
	char value[1024+ 1];
}PagesGetInfo_detail_info;

typedef struct
{
	char info[0 + 1];
	char key[128 + 1];
	char value[1024+ 1];
}PagesGetInfo_contact_info;

typedef struct
{
	int page_id;
	char name[128 + 1];
	char headurl[256 + 1];
	char mainurl[256 + 1];
	int  nSize_status;  //Save the array size by code_gen tools. 
	PagesGetInfo_status*  status;
	char desc[1024 + 1];
	int  nSize_base_info;  //Save the array size by code_gen tools. 
	PagesGetInfo_base_info*  base_info;
	int  nSize_detail_info;  //Save the array size by code_gen tools. 
	PagesGetInfo_detail_info*  detail_info;
	int  nSize_contact_info;  //Save the array size by code_gen tools. 
	PagesGetInfo_contact_info*  contact_info;
	int albums_count;
	int blogs_count;
	int fans_count;
}tResponsePagesGetInfo;


extern void* RenRenAPI_JsonParse_PagesGetInfo(char *text);
#endif
