/*!
*@FileName: RenRenAPI_Profile.h
*@Author: zengying@GoZone
*@Date: 2010-12-22
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_PROFILE_H__
#define  __RENRENAPI_PROFILE_H__

#include "RenRenAPI.h"

typedef struct
{
	char birth_year[8*3 + 1];
	int birth_month;
	int birth_day;
}Profile_birth;

typedef struct
{
	char province[32*3 + 1];
	char city[32*3 + 1];
}Profile_hometown;

typedef struct
{
	char gender[32*3 + 1];
	int  nSize_birth;  //Save the array size by code_gen tools. 
	Profile_birth*  birth;
	int  nSize_hometown;  //Save the array size by code_gen tools. 
	Profile_hometown*  hometown;
}Profile_base_info;

typedef struct
{
	char content[256*3 + 1];
	char time[32*3 + 1];
}Profile_status;

typedef struct
{
	int uid;
	char name[32*3 + 1];
	char headurl[256*3 + 1];
	int star;
	char network_name[128*3 + 1];
	int  nSize_base_info;  //Save the array size by code_gen tools. 
	Profile_base_info*  base_info;
	int  nSize_status;  //Save the array size by code_gen tools. 
	Profile_status*  status;
	int visitors_count;
	int blogs_count;
	int albums_count;
	int friends_count;
	int guestbook_count;
}tResponseProfile;


extern void* RenRenAPI_JsonParse_Profile(char *text);
#endif
