/*!
*@FileName: RenRenAPI_FriendsAreFriends.h
*@Author: lee-5959f8a390f@GoZone
*@Date: 2011-6-16
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_FRIENDSAREFRIENDS_H__
#define  __RENRENAPI_FRIENDSAREFRIENDS_H__

#include "RenRenAPI.h"

typedef struct
{
	int uid1;
	int uid2;
	int are_friends;
}tResponseFriendsAreFriendsItem;

typedef struct
{
	int	nArraySize;
	tResponseFriendsAreFriendsItem*	Array;
}tResponseFriendsAreFriends;


extern void* RenRenAPI_JsonParse_FriendsAreFriends(char *text);
#endif
