/*!
*@FileName: RenRenAPI_GuestbookPost.cpp
*@Author: pengzhixiong@GoZone
*@Date: 2011-1-4
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by ReeRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#include "RenRenAPICommon.h"

/**
 * JsonÎÄ¼þ½âÎö
 *
 * \param text
 *
 * \return 
 */
void* RenRenAPI_JsonParse_GuestbookPost(char *text)
{
	cJSON *json;
	cJSON *pTemp0;
	tResponseGuestbookPost*  Response = new tResponseGuestbookPost;
	memset(Response, 0 , sizeof(tResponseGuestbookPost));

	json = cJSON_Parse(text);

	pTemp0 = cJSON_GetObjectItem(json, "id");
	if(pTemp0)
	{
		Response->id = pTemp0->valueint;
	}



	cJSON_Delete(json);
	return Response;
}