/*!
*@FileName: RenRenAPI_StatusGet.cpp
*@Author: zengying@GoZone
*@Date: 2010-12-24
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by ReeRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#include "RenRenAPICommon.h"

/**
 * JsonÎÄ¼þ½âÎö
 *
 * \param text
 *
 * \return 
 */
void* RenRenAPI_JsonParse_StatusGet(char *text)
{
	cJSON *json;
	cJSON *pTemp0;
	tResponseStatusGet*  Response = new tResponseStatusGet;
	memset(Response, 0 , sizeof(tResponseStatusGet));

	json = cJSON_Parse(text);

	pTemp0 = cJSON_GetObjectItem(json, "uid");
	if(pTemp0)
	{
		Response->uid = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "status_id");
	if(pTemp0)
	{
		Response->status_id = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "time");
	if(pTemp0)
	{
		STRCPY_Ex(Response->time, pTemp0->valuestring);
	}
	pTemp0 = cJSON_GetObjectItem(json, "message");
	if(pTemp0)
	{
		STRCPY_Ex(Response->message, pTemp0->valuestring);
	}
	pTemp0 = cJSON_GetObjectItem(json, "comment_count");
	if(pTemp0)
	{
		Response->comment_count = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "source_name");
	if(pTemp0)
	{
		STRCPY_Ex(Response->source_name, pTemp0->valuestring);
	}
	pTemp0 = cJSON_GetObjectItem(json, "source_url");
	if(pTemp0)
	{
		STRCPY_Ex(Response->source_url, pTemp0->valuestring);
	}



	cJSON_Delete(json);
	return Response;
}