/*!
*@FileName: RenRenAPI_FriendsGetFriends.h
*@Author: pengzhixiong@GoZone
*@Date: 2010-12-21
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_FRIENDSGETFRIENDS_H__
#define  __RENRENAPI_FRIENDSGETFRIENDS_H__

#include "RenRenAPI.h"

typedef struct
{
	int id;
	char name[64*3 + 1];
	char headurl[255 + 1];
	char tinyurl[255 + 1];
	char tinyurl_with_logo[255 + 1];
	char headurl_with_logo[256 + 1];
}tResponseFriendsGetFriendsItem;


typedef struct
{
	int  nArraySize;  //Save the array size by code_gen tools. 
	tResponseFriendsGetFriendsItem*  Array;
}tResponseFriendsGetFriends;

extern void* RenRenAPI_JsonParse_FriendsGetFriends(char *text);
#endif
