/*!
*@FileName: RenRenAPI_FriendsSearch.h
*@Author: pengzhixiong@GoZone
*@Date: 2011-2-25
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_FRIENDSSEARCH_H__
#define  __RENRENAPI_FRIENDSSEARCH_H__

#include "RenRenAPI.h"

typedef struct
{
	int id;
	char name[64 + 1];
	char tinyurl[256 + 1];
	char info[512 + 1];
	int isFriend;
}FriendsSearch_friends;

typedef struct
{
	int total;
	int  nSize_friends;  //Save the array size by code_gen tools. 
	FriendsSearch_friends*  friends;
}tResponseFriendsSearch;


extern void* RenRenAPI_JsonParse_FriendsSearch(char *text);
#endif
