/*!
*@FileName: RenRenAPI_PhotosGet.h
*@Author: xuhonglei@GoZone
*@Date: 2010-12-30
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_PHOTOSGET_H__
#define  __RENRENAPI_PHOTOSGET_H__

#include "RenRenAPI.h"

typedef struct
{
	double pid;
	int aid;
	int uid;
	char url_tiny[256 + 1];
	char url_head[256 + 1];
	char url_large[256 + 1];
	char caption[RENREN_LENGTH_PHOTO_COMMENT*3 + 1];
	char time[64 + 1];
	int view_count;
	int comment_count;
}tResponsePhotosGetItem;

typedef struct
{
	int	nArraySize;
	tResponsePhotosGetItem*	Array;
}tResponsePhotosGet;


extern void* RenRenAPI_JsonParse_PhotosGet(char *text);
#endif
