/*!
*@FileName: RenRenAPI_PhotosGetAlbums.h
*@Author: xuhonglei@GoZone
*@Date: 2010-12-28
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_PHOTOSGETALBUMS_H__
#define  __RENRENAPI_PHOTOSGETALBUMS_H__

#include "RenRenAPI.h"

typedef struct
{
	int visable;	// 99(所有人),4(密码保护) 3(同网络人),1(好友), , -1(仅自己可见)
	int comment_count;
	int uid;
	char update_time[64 + 1];
	char location[128 + 1];
	char description[256 + 1];
	char name[256 + 1];
	char create_time[64 + 1];
	int aid;
	int type;
	char url[256 + 1];
	int size;
}tResponsePhotosGetAlbumsItem;

//此结构可以获得json文件中的记录数量
typedef struct
{
	int	nArraySize;
	tResponsePhotosGetAlbumsItem*	Array;
}tResponsePhotosGetAlbums;


extern void* RenRenAPI_JsonParse_PhotosGetAlbums(char *text);
#endif
