/*!
*@FileName: RenRenAPI_BlogGet.cpp
*@Author: zengying@GoZone
*@Date: 2010-12-27
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by ReeRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#include "RenRenAPICommon.h"


/**
 * JsonÎÄ¼þ½âÎö
 *
 * \param text
 *
 * \return 
 */
void* RenRenAPI_JsonParse_BlogGet(char *text)
{
	cJSON *json;
	cJSON *pTemp0;
	tResponseBlogGet*  Response = new tResponseBlogGet;
	memset(Response, 0 , sizeof(tResponseBlogGet));

	json = cJSON_Parse(text);

	pTemp0 = cJSON_GetObjectItem(json, "uid");
	if(pTemp0)
	{
		Response->uid = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "id");
	if(pTemp0)
	{
		Response->id = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "view_count");
	if(pTemp0)
	{
		Response->view_count = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "comment_count");
	if(pTemp0)
	{
		Response->comment_count = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "visable");
	if(pTemp0)
	{
		Response->visable = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "title");
	if(pTemp0)
	{
		STRCPY_Ex(Response->title, pTemp0->valuestring);
	}
	pTemp0 = cJSON_GetObjectItem(json, "content");
	if(pTemp0)
	{
		STRCPY_Ex(Response->content, pTemp0->valuestring);
	}
	pTemp0 = cJSON_GetObjectItem(json, "name");
	if(pTemp0)
	{
		STRCPY_Ex(Response->name, pTemp0->valuestring);
	}
	pTemp0 = cJSON_GetObjectItem(json, "headurl");
	if(pTemp0)
	{
		STRCPY_Ex(Response->headurl, pTemp0->valuestring);
	}
	pTemp0 = cJSON_GetObjectItem(json, "time");
	if(pTemp0)
	{
		STRCPY_Ex(Response->time, pTemp0->valuestring);
	}



	cJSON_Delete(json);
	return Response;
}