/*!
*@FileName: RenRenAPI_MessageGets.cpp
*@Author: pengzhixiong@GoZone
*@Date: 2010-12-27
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by ReeRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#include "RenRenAPICommon.h"

/**
 * JsonÎÄ¼þ½âÎö
 *
 * \param text
 *
 * \return 
 */
void* RenRenAPI_JsonParse_MessageGets(char *text)
{
	cJSON *json;
	cJSON *pTemp0;
	tResponseMessageGets*  Response = new tResponseMessageGets;
	memset(Response, 0 , sizeof(tResponseMessageGets));

	json = cJSON_Parse(text);

	pTemp0 = cJSON_GetObjectItem(json, "unread_count");
	if(pTemp0)
	{
		Response->unread_count = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "count");
	if(pTemp0)
	{
		Response->count = pTemp0->valueint;
	}
	pTemp0 = cJSON_GetObjectItem(json, "messages");
	if(pTemp0)
	{
		int nSize1 = 0, i = 0;
		nSize1 = cJSON_GetArraySize(pTemp0);
		Response->nSize_messages = nSize1;
		if( nSize1 != 0 )
		{
			Response->messages = NULL;
			Response->messages = (MessageGets_messages*) malloc(sizeof( MessageGets_messages ) * nSize1 );
			memset(Response->messages, 0 , sizeof(MessageGets_messages) * nSize1 );
		}
		for ( i = 0; i < nSize1; i++ )
		{
			cJSON *Item1 = NULL, *pTemp1 = NULL;
			Item1 = cJSON_GetArrayItem(pTemp0,i);
			pTemp1 = cJSON_GetObjectItem(Item1, "id");
			if(pTemp1)
			{
				Response->messages[i].id = pTemp1->valueint;
			}
			pTemp1 = cJSON_GetObjectItem(Item1, "uid");
			if(pTemp1)
			{
				Response->messages[i].uid = pTemp1->valueint;
			}
			pTemp1 = cJSON_GetObjectItem(Item1, "name");
			if(pTemp1)
			{
				STRCPY_Ex(Response->messages[i].name, pTemp1->valuestring);
			}
			pTemp1 = cJSON_GetObjectItem(Item1, "head_url");
			if(pTemp1)
			{
				STRCPY_Ex(Response->messages[i].head_url, pTemp1->valuestring);
			}
			pTemp1 = cJSON_GetObjectItem(Item1, "time");
			if(pTemp1)
			{
				STRCPY_Ex(Response->messages[i].time, pTemp1->valuestring);
			}
			pTemp1 = cJSON_GetObjectItem(Item1, "title");
			if(pTemp1)
			{
				STRCPY_Ex(Response->messages[i].title, pTemp1->valuestring);
			}
			pTemp1 = cJSON_GetObjectItem(Item1, "content");
			if(pTemp1)
			{
				STRCPY_Ex(Response->messages[i].content, pTemp1->valuestring);
			}
			pTemp1 = cJSON_GetObjectItem(Item1, "is_read");
			if(pTemp1)
			{
				Response->messages[i].is_read = pTemp1->valueint;
			}

		}
	}


	cJSON_Delete(json);
	return Response;
}