/*!
*@FileName: RenRenAPI_StatusGet.h
*@Author: zengying@GoZone
*@Date: 2010-12-24
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_STATUSGET_H__
#define  __RENRENAPI_STATUSGET_H__

#include "RenRenAPI.h"

typedef struct
{
	int uid;
	int status_id;
	char time[64 + 1];
	char message[256 + 1];
	int comment_count;
	char source_name[64 + 1];
	char source_url[256 + 1];
}tResponseStatusGet;


extern void* RenRenAPI_JsonParse_StatusGet(char *text);
#endif
