/*!
*@FileName: RenRenForm_PhotoDetail.h
*@Author: xuhonglei@GoZone
*@Date: 2011-1-4
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENFORM_PHOTODETAIL_H__
#define  __RENRENFORM_PHOTODETAIL_H__

#include "RenRenAPI.h"

typedef enum
{
	RR_PrePhoto,			
	RR_NextPhoto = 1,		

	RR_ViewPhotoTypeEnd,
}RR_ViewPhotoType;


class TPhotoDetailForm : public TWindow
{
public:
	TPhotoDetailForm(TApplication* pApp, int i, int m_nAlbumPhotoCount, Boolean bSingleMode = FALSE);
	virtual ~TPhotoDetailForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);
	

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSetFocusEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlKillFocusEvent(TApplication * pApp, EventType * pEvent);	
	Boolean _OnFldChangedEvent(TApplication * pApp, EventType* pEvent);

	Int32 _ViewPhoto(TApplication* pApp, RR_ViewPhotoType ViewType);
	Int32 _SetViewButtonEnabled(Boolean bEnabled);
	Int32 _SetViewButtonVisiable(Boolean bEnabled);	
	Int32 _SetCtrlsData(TApplication* pApp);
	Int32 _SetCtrlsStyle(TApplication* pApp);
private:
	Int32 m_TitleBtnLeft;	//标题左边按钮ID
	Int32 m_TitleBtnRight;//标题右边按钮ID
	Int32 m_TitleCrtlID;	//标题文本ID
	Int32 m_CaptionID;	//
	Boolean m_bSingleMode;	//单张模式 

	int m_index;      //记录照片编号
	int m_photosCount;//记录相册中数量
	int m_photosPos;  //翻页的相册编号
	char m_uid[32];
	char m_pid[32];
	
	//图片
	TBitmap* pPhotoBmp;
	Int32 m_nAlbumPhotoCount;
	Int32 m_TitleButtonCtlID;//标题按钮, 显示专辑或者照片

	TUChar         	pszFilePath[EOS_FILE_MAX_PATH];	
};

#endif
