/*!
*@FileName: RenRenForm_GuestbookGet.h
*@Author: pengzhixiong@GoZone
*@Date: 2010-12-30
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENFORM_GUESTBOOKGET_H__
#define  __RENRENFORM_GUESTBOOKGET_H__

#include "RenRenAPI.h"

#define GUESTBOOKLIST_MAXITEM		(200)
typedef struct
{
	double id;
	Int32 uid;				//id
	Int32 HeadMaskButtonID;	//
	TBitmap* pBmp;		//Bmp
	TBitmap* pBmpZoom;		//Bmp
	Int32 TButtonReplyID; //回复ID
	Boolean bWhisper;		//悄悄话,回复默认也要是悄悄话	
}tGuestbookList_ItemData;

class TGuestbookGetForm : public TWindow
{
public:
	TGuestbookGetForm(TApplication* pApp, eFormMode nFormMode, Boolean bNew = TRUE);
	virtual ~TGuestbookGetForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSetFocusEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlKillFocusEvent(TApplication * pApp, EventType * pEvent);	
	Boolean _OnFldChangedEvent(TApplication * pApp, EventType* pEvent);
	Boolean _UpdateProfilePhoto(TApplication* pApp, tResponseUsersGetInfo* ResponseInfoPhoto);
private:
	char*  m_uid;
	eFormMode  m_FormMode;
	Int32 m_TitleBtnLeft;	//标题左边按钮ID
	Int32 m_TitleBtnRight;	//标题右边按钮ID
	sBottomTabCtrID 	BottomTabCtrID;	//底部Tab的控件ID	
	TBitmap * pProfileImage;	//Profile的头像
	Int32       m_ProfileImageID;
	
	Boolean bReply;
	Int32 m_SelectReplyItem;
	tGuestbookList_ItemData gItemData[GUESTBOOKLIST_MAXITEM];			
};

#endif
