/*!
*@FileName: RenRenForm_WebPanel.h
*@Author: pengzhixiong@GoZone
*@Date: 2010-12-23
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENFORM_WEBPANEL_H__
#define  __RENRENFORM_WEBPANEL_H__

#include "RenRenAPI.h"
#include "TCOM_TBrowser_WebPanel.h"
//#include "TCOM_TBrowser_WebClient_EventHandler.h"

class TWebPanelForm : public TWindow
{
public:
	TWebPanelForm(TApplication * pApp, const TUChar* in_pszTitle, const char* in_pszURL);
	virtual ~TWebPanelForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);
	void SetText(const TUChar* pszTitle, const char* pURL, const char* pDes);
private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSetFocusEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlKillFocusEvent(TApplication * pApp, EventType * pEvent);	
	Boolean _OnFldChangedEvent(TApplication * pApp, EventType* pEvent);	
private:
	Int32 m_TitleBtnLeft;	//标题左边按钮ID
	Int32 m_TitleBtnRight;	//标题右边按钮ID

	TUChar* pszTitle;
	char* pszURL;

	Int32	m_BackBtn;	
	TBrowser::TCOM_WebClient_Interface* m_pWebPanelTComObj;
	TBrowser::TWebPanel* m_pWebPanel;	
};
#endif
