/*!
*@FileName: RenRenForm_PhotosGet.h
*@Author: xuhonglei@GoZone
*@Date: 2010-12-30
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENFORM_PHOTOSGET_H__
#define  __RENRENFORM_PHOTOSGET_H__

#include "RenRenAPI.h"

#define PHOTOLIST_MAXITEM  (240)

typedef struct
{	
	Int32 nThumbnailImageID;//存TImage Ctrl ID
	TImage* pThumbnailImage;//存TImage Ctrl 指针
	TBitmap* pThumbnailBmp;	
}tPhotosGet_ItemData;

class TPhotosGetForm : public TWindow
{
public:
	TPhotosGetForm(TApplication* pApp);
	virtual ~TPhotosGetForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSetFocusEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlKillFocusEvent(TApplication * pApp, EventType * pEvent);	
	Boolean _OnFldChangedEvent(TApplication * pApp, EventType* pEvent);	
	Int32 _CreateAlbumPhotos(TApplication* pApp, tResponsePhotosGet* Response);
	Int32 _SetFormTilte(TApplication * pApp);

	Int32 _SetCtrlsData(TApplication* pApp, tResponsePhotosGet* Response);
	Int32 _SetViewButtonEnabled(Boolean bEnabled);
	Int32 _SetCtrlsStyle(TApplication* pApp);

private:
	Int32 m_TitleBtnLeft;	//标题左边按钮ID
	Int32 m_TitleBtnRight;	//标题右边按钮ID

	//相册缩略图
	Int32 m_nAlbumPhotoCount;

	Int32 m_TitleButtonCtlID;//标题照片按钮
	char m_AlbumId[32];
	char m_AlbumTitle[256];
	Int32	m_BackBtn;

	TBitmap* pPhotoBmp;
	Int32 m_TitleCrtlID;	//标题文本ID

	int m_AlbumPhotosCount;	//专辑中的照片总数
	int m_CommentCount;	//专辑的评论数
	
	int m_index;      //记录照片编号
	Boolean  bAlbumMode;	//是否是专辑浏览模式
	char m_uid[32];
	char m_pid[32];

	tPhotosGet_ItemData gItemData[PHOTOLIST_MAXITEM];	

	TUChar         	pszFilePath[EOS_FILE_MAX_PATH];
};

#endif
