/*!
*@FileName: RenRenForm_StatusGetComment.h
*@Author: zbingwen@GoZone
*@Date: 2011-1-10
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENFORM_STATUSGETCOMMENT_H__
#define  __RENRENFORM_STATUSGETCOMMENT_H__

#include "RenRenAPI.h"

#define STATUSGETCOMMENT_MAXITEM	(200)


typedef struct
{
	Int32 uid;				//id
	Int32 status_id;
	Int32 HeadMaskButtonID;	//	
	TBitmap* pBmp;		//Bmp
	Int32 OptionButtonID;
	Int32 NameID;
}tStatusGetComments_ItemData;

class TStatusGetCommentForm : public TWindow
{
public:
	TStatusGetCommentForm(TApplication* pApp, Boolean bNew = TRUE);
	virtual ~TStatusGetCommentForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSetFocusEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlKillFocusEvent(TApplication * pApp, EventType * pEvent);	
	Boolean _OnFldChangedEvent(TApplication * pApp, EventType* pEvent);	
	Boolean _UpdateList(TApplication * pApp, tResponseStatusGetComment* Response);	
private:
	Int32 m_TitleBtnLeft;	//标题左边按钮ID
	Int32 m_TitleBtnRight;	//标题右边按钮ID
	Int32 m_MoreBtn;
	Coord m_OffsetY;			//新加评论条目的起始位置
	Int32 m_ItemCount;		//条数统计,包括更多的
	
	tStatusGetComments_ItemData gItemData[STATUSGETCOMMENT_MAXITEM];	
};

#endif
