/*!
*@FileName: RenRenForm_BlogGets.h
*@Author: zengying@GoZone
*@Date: 2010-12-24
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENFORM_BLOGGETS_H__
#define  __RENRENFORM_BLOGGETS_H__

#include "RenRenAPI.h"


#define RR_BLOG_ITEM_NUM_MAX			(100)

class TBlogGetsForm : public TWindow
{
public:
	TBlogGetsForm(TApplication* pApp, eFormMode nFormMode, Boolean bNew = TRUE);
	virtual ~TBlogGetsForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSetFocusEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlKillFocusEvent(TApplication * pApp, EventType * pEvent);	
	Boolean _OnFldChangedEvent(TApplication * pApp, EventType* pEvent);
	Boolean _UpdateProfilePhoto(TApplication* pApp, tResponseUsersGetInfo* ResponseInfoPhoto);
private:
	tResponseBlogGets* Response;
	char*	m_uid;
	eFormMode m_FormMode;
	Int32 m_TitleBtnLeft;	//标题左边按钮ID
	Int32 m_TitleBtnRight;	//标题右边按钮ID
	sBottomTabCtrID 	BottomTabCtrID;	//底部Tab的控件ID	
	TBitmap * pProfileImage;	//Profile的头像
	Int32       m_ProfileImageID;
	
};

#endif
