/*!
*@FileName: RenRenForm_MessageGet.h
*@Author: pengzhixiong@GoZone
*@Date: 2010-12-24
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENFORM_MESSAGEGET_H__
#define  __RENRENFORM_MESSAGEGET_H__

#include "RenRenAPI.h"
#include "TCOM_TBrowser_WebPanel.h"

#define MESSAGEGET_MAXITEM	(50)

typedef struct
{
	Int32 uid;				//id
	char name[64 + 1];
	Int32 HeadMaskButtonID;	//	
	TBitmap* pBmp;		//Bmp
	Int32 OptionButtonID;
	Int32 NameID;
}tMessageGet_ItemData;

class TMessageGetForm : public TWindow
{
public:
	TMessageGetForm(TApplication* pApp, Boolean bNew = TRUE);
	virtual ~TMessageGetForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSetFocusEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlKillFocusEvent(TApplication * pApp, EventType * pEvent);	
	Boolean _OnFldChangedEvent(TApplication * pApp, EventType* pEvent);	
private:
	Int32 m_TitleBtnLeft;	//标题左边按钮ID
	Int32 m_TitleBtnRight;	//标题右边按钮ID
	sBottomOptionCtrID  BottomOptionCtrID;		//Option控件ID
	char  m_uid[32];
	tMessageGet_ItemData gItemData[MESSAGEGET_MAXITEM];	
	
	TBrowser::TWebPanel* m_pWebPanel;
};

#endif
