/*!
*@FileName: RenRenForm_BlogGet.h
*@Author: zengying@GoZone
*@Date: 2010-12-27
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENFORM_BLOGGET_H__
#define  __RENRENFORM_BLOGGET_H__

#include "RenRenAPI.h"
#include "TCOM_TBrowser_WebPanel.h"

class TBlogGetForm : public TWindow
{
public:
	TBlogGetForm(TApplication* pApp, Boolean bNew = TRUE);
	virtual ~TBlogGetForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSetFocusEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlKillFocusEvent(TApplication * pApp, EventType * pEvent);	
	Boolean _OnFldChangedEvent(TApplication * pApp, EventType* pEvent);	
private:
	tResponseBlogGet* Response;
	
	Int32 m_TitleBtnLeft;	//标题左边按钮ID
	Int32 m_TitleBtnRight;	//标题右边按钮ID
	sBottomOptionCtrID  BottomOptionCtrID;		//Option控件ID
	Int32 nHeadMaskBtnID;
	TBitmap* pPhotoBmp;
	TBitmap* pPhotoBmpZoom;

	TBrowser::TWebPanel* m_pWebPanel;	

	char  m_id[32];
	char m_uid[32];
};

#endif
