/*!
*@FileName: RenRenForm_UsersGetEvent.h
*@Author: zbingwen@GoZone
*@Date: 2010-12-24
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENFORM_USERSGETEVENT_H__
#define  __RENRENFORM_USERSGETEVENT_H__

#include "RenRenAPI.h"

class TUsersGetEventForm : public TWindow
{
public:
	TUsersGetEventForm(TApplication* pApp, Boolean bNew = TRUE);
	virtual ~TUsersGetEventForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);
	Boolean UpdateEvent(TApplication * pApp);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSetFocusEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlKillFocusEvent(TApplication * pApp, EventType * pEvent);	
	Boolean _OnFldChangedEvent(TApplication * pApp, EventType* pEvent);	
private:
	Int32 m_TitleBtnLeft;	//标题左边按钮ID
	Int32 m_TitleBtnRight;	//标题右边按钮ID
};

#endif
