/*!
*@FileName: RenRenForm_InitialLogin.h
*@Author: pengzhixiong@GoZone
*@Date: 2010-12-13
*@Log: 	Author 			Date 		Description
*
*@section Copyright
* =======================================================================<br>
*          Copyright ? 2010-2012 GOZONE <br>
*                All Rights Reserved.<br>
* The file is generated by RenRen_Component Wizard for Tranzda Mobile Platform <br>
* =======================================================================<br>
*/

#ifndef  __RENRENAPI_INITIALOGIN_H__
#define  __RENRENAPI_INITIALOGIN_H__

#include "RenRenAPI.h"


class TInitialLoginForm : public TWindow
{
public:
	TInitialLoginForm(TApplication* pApp);
	virtual ~TInitialLoginForm(void);
	virtual Boolean EventHandler(TApplication * appP, EventType * eventP);

private:
	Boolean _OnWinInitEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnWinClose(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSelectEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlSetFocusEvent(TApplication * pApp, EventType * pEvent);
	Boolean _OnCtrlKillFocusEvent(TApplication * pApp, EventType * pEvent);	
	Boolean _OnFldChangedEvent(TApplication * pApp, EventType* pEvent);	
private:
	Int32 m_TitleBtnLeft;		//标题左边按钮ID
	Int32 m_TitleBtnRight;	//标题右边按钮ID
	//第一次点击显示密码是否需要清空密码
	Boolean bCleanPwdWhenFirstShowPwd;
};

#endif
